<?php
$translate = $this->plugin('translate');

$annotations = $this->vars('annotations');
$item = $this->vars('item');

//construction des datas
$data = [];
$recommandations = [];
$doublonsEval = [];
foreach ($annotations as $a) {
    $cId = $a->value('dcterms:creator')->valueResource()->id();
    if(isset($doublonsEval[$cId])) $e = $recommandations[$doublonsEval[$cId]];
    else {
        $doublonsEval[$cId]=count($recommandations);
        $e = [            
            'creator'=>$a->value('dcterms:creator')->valueResource()->linkPretty(),
            'evals'=>[
                ['niv'=>'Master','nb'=>0,'sum'=>0, 'id'=>$cId],
                ['niv'=>'Licence','nb'=>0,'sum'=>0, 'id'=>$cId]
            ]
        ];
    }
    $d = [
        'creator'=>$a->value('dcterms:creator')->valueResource()->linkPretty()
        ,'contributor'=>$a->value('dcterms:contributor') ? $a->value('dcterms:contributor')->valueResource()->linkPretty() : ''
        ,'date'=>$a->created()->format('Y-m-d H:i:s')
        ,'url'=>$a->url()
        ,'urlAdmin'=>$a->adminUrl()
        ,'urlHypo'=>$a->value('schema:acquiredFrom') ? $a->value('schema:acquiredFrom')->uri() : ''
    ];
    $targets = $a->targets();
    if (count($targets)){
        foreach ($targets as $target){            
            $tv = $target->value('rdf:value',['all'=>true]);
            foreach ($tv as $v) {
                if($v->valueResource())$d['target']=$v->valueResource()->linkPretty();
                else{
                    $vs = json_decode($v->__toString(),true);
                    foreach ($vs as $k => $v) {
                        if($k!='type')$d[$k]=$v;
                    }    
                }
            }
        }
    }
    $bodies = $a->bodies();
    if (count($bodies)){
        foreach ($bodies as $body){            
            $bv = $body->value('rdf:value',['all'=>true]);
            foreach ($bv as $b) {
                //gestion des évaluations
                if($b->valueResource())$e=getRateItem($b->valueResource(), $e);
                $d['body']=$b->__toString();
            }
        }
    }
    if(!$item->value('dcterms:source')){
        if($a->value('oa:hasSource'))
           $d['source'] = $a->value('oa:hasSource')->asHtml();
    }

    if($e['evals'][0]['nb'] || $e['evals'][1]['nb']) $recommandations[$doublonsEval[$cId]] = $e;
    else $data[] = $d;
}

$t = 1;

function getRateItem($br, $e){
    foreach ($e['evals'] as $i=>$k) {
        if($br->value('ma:isRatingOf')->__toString()=="rateItemFor".$k['niv']){
            $rate = floatval($br->value('ma:hasRating')->__toString());
            $e['evals'][$i]['sum'] += $rate;
            $e['evals'][$i]['nb']++; 
        }
    }
    return $e;
}


?>

<!--
<h3><?php echo $translate('Recommandations'); ?></h3>
<div id="recommandationsDetails" class="h-50 d-inline-block" style="overflow: scroll;"></div>
-->

<h3><?php echo $translate('Annotations'); ?></h3>
<div id="annoDetails" class="h-50 d-inline-block" style="overflow: scroll;"></div>
<script>
    let dtAnno = <?php echo json_encode($data);?>;
    
    showAnno(dtAnno);

    let dtEval = <?php echo json_encode($recommandations);?>;
    showRecommandations(dtEval);
    $('#ddRecommandationsListe .kv-fa').rating({
        theme: 'krajee-fa',
        filledStar: '<i class="fa fa-star"></i>',
        emptyStar: '<i class="fa fa-star"></i>',
        showClear:false,
        showCaption:false,
        readonly:true
    });

   function showRecommandations(evals){

    let rowCreator = d3.select('#ddRecommandationsListe').selectAll('li').data(evals).enter()
            .append('li').append('a')
                .attr('class','dropdown-item')
                .attr('href','#')
                .append('div').attr('class','container-fluid')
                .append('div').attr('class','row');
    let divEval = rowCreator.selectAll('div').data(d=>d.evals).enter().append('div').attr('class','col')
        .append('form').attr('class','d-flex justify-content-start');
    divEval.append('label')
        .attr('for',d=>'rateItemFor'+d.niv+d.id)
        .attr('style','padding-top: 3px;')
        .html(d=>d.niv);
    divEval.append('input')
        .attr('id',d=>'rateItemFor'+d.niv+d.id)
        .attr('type','text')
        .attr('data-size','xs')
        .attr('value',d=>d.nb ? d.sum/d.nb:0)
        .attr('class','kv-fa rating-loading');

    rowCreator.append('div')
                .attr('class','col')
                .html(d=>d.creator);        

       /*
        let divCreator = d3.select('#recommandationsDetails').selectAll('div').data(evals).enter()
            .append('div')
                .attr('class','border-bottom border-danger')
                .append('div')
                .html(d=>'<h5>'+d.creator+' :</h5>');
        let divEval = divCreator.selectAll('div').data(d=>d.evals).enter().append('div').attr('class','mb-8 row');
        divEval.append('label')
            .attr('for',d=>'rateItemFor'+d.niv+d.id)
            .attr('class','col-sm-2 col-form-label')
            .html(d=>d.niv);
        divEval.append('div').attr('class','col-sm-3').append('input')
            .attr('id',d=>'rateItemFor'+d.niv+d.id)
            .attr('type','text')
            .attr('data-size','xs')
            .attr('value',d=>d.nb ? d.sum/d.nb:0)
            .attr('class','kv-fa rating-loading');
        */

   }
   function showAnno(dtAnno){
    dtAnno.sort(function(a, b) {
        return a.start - b.start;
    });
    let divAnno = d3.select('#annoDetails').selectAll('div').data(dtAnno).enter()
        .append('div')
            .attr('class','border-bottom border-danger');
    divAnno.append('div')
        .html(d=>d.source ? '<h5>Source :</h5>'+d.source : '');
    divAnno.append('div')
        .html(d=>d.target ? '<h5>Mot-clefs :</h5>'+d.target : '');
    divAnno.append('div')
            .html(d=>d.exact ? '<h5>Citation :</h5>' : '')
            .append('span')
                .attr('class',"fs-6 fst-italic")
                .text(d=>d.exact ? d.exact : '');
    divAnno.append('div')
            //.html(d=>d.body ? '<h5>Commentaire de '+d.creator+' :</h5><h6>'+d.contributor+'</h6>' : '')
            .html(d=>d.body ? '<h5>Commentaire de '+d.creator+' :</h5>' : '')
            .append('span')
                .attr('class',"fs-6 lh-1")
                .text(d=>d.body && !d.target ? d.body : '');
    divAnno.append('i')
            .attr('class',"fas fa-external-link-alt")
            .style('margin','1em')
            .on('click',(e,d)=>window.open(d.url,'_blank'));
    divAnno.append('img')
            .attr('class',"icon-hypothesis")
            .attr('src','<?php echo $this->assetUrl('img/logo_hypothesis.png');?>')
            .on('click',(e,d)=>window.open(d.urlHypo,'_blank'));
    divAnno.append('i')
            .attr('class',"fas fa-edit")
            .style('margin','1em')
            .on('click',(e,d)=>window.open(d.urlAdmin,'_blank'));
    /*
    let eval = divAnno.append('div')
        .attr('class',"evalRange");
    eval.append('label')
        .attr('class', 'lblRangeG')
        .text('inutile');
    eval.append('input')
        .attr('class', 'form-control-range')
        .attr('type',"range")
        .attr('max',100)
        .attr('min',0);
    eval.append('label')
        .attr('class', 'lblRangeD')
        .text('utile');
    */
   }

</script>

