<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$item = $this->vars('item');
$site = $this->vars('site');
$embedMedia = $this->vars('embedMedia');
$itemMedia = $item->media();
$item->displayValues();

//construction de la source de l'iframe
$srcIframe = "";
if($item->resourceClass() && $item->resourceClass()->label()=="Webpage"){
    $srcIframe = $item->value('dcterms:source')->uri();
}
//récupération des annotations
$relations = $item->subjectValues();
$annotations = [];
foreach ($relations as $k => $r) {
    foreach ($r as $v) {
        $vr = $v->resource();
        if($vr->resourceClass() && $vr->resourceClass()->label()=="Annotation"){
            $annotations[]=$vr;
        }
    }
}

?>
<div class="container">
    <div class="row">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><?php echo $translate('Item sets').' : '; ?></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <?php foreach ($itemSets as $itemSet): ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <?php endif; ?>
    </div>
    <div class="row">
        <?php echo $item->value('dcterms:source') ? $item->value('dcterms:source')->asHtml() : '';?>
    </div>
    <div class="row">
        <div class="col-8">
            <?php if ($srcIframe): ?>
            <iframe id="ifSource" width="100%" height="560px" src="<?php echo $srcIframe;?>">
            </iframe>
            <?php else: ?>
                <?php if ($embedMedia && $itemMedia): ?>
                    <div class="media-embeds">
                        <?php foreach ($itemMedia as $media):
                            echo $media->render();
                        endforeach;
                        ?>
                    </div>
                    <?php endif; ?>

                    <?php echo $item->displayValues(); ?>

                    <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
                    <div class="property">
                        <h4><?php echo $translate('Site pages'); ?></h4>
                        <div class="values">
                            <?php foreach ($sitePages as $sitePage): ?>
                            <div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php if (!$embedMedia && $itemMedia): ?>
                    <div class="media-list">
                        <?php foreach ($itemMedia as $media): ?>
                        <?php echo $media->linkPretty(); ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

            <?php endif; ?>
        </div>
        <div class="col-4" style="height: 560px;padding-bottom: 20px;">
            <?php echo $this->partial('uoh/annotations', ['annotations'=>$annotations,'item'=>$item]);?>
        </div>
    </div>
</div>




