<footer class="container page-footer font-small">
    <p style="padding-top: 6px;">Design by 
    <a href="https://samszo.univ-paris8.fr/" >Samuel Szoniecky</a>
    <a href="https://samszo.univ-paris8.fr/" >Jean-Marc Meunier</a>
    <a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
            <img style="height: 40px;" src="<?php echo $this->assetUrl('img/logo_paragraphe.gif'); ?>" alt="Laboratoire Paragraphe" />
    </p>            
</footer>
