<?php
$site = $this->vars('site');
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
?>


<ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
<?php foreach($container as $page): ?>
    <li class="nav-link px-2 <?php if($activePage && $page->label == $activePage['page']->label) echo 'class="list-inline-item active"';?>">
    <?php echo $this->navigation()->menu()->htmlify($page) . PHP_EOL; ?>
    </li>
<?php endforeach; ?>
</ul>

